#
# Create own Debian based RaspberyPI images
#
# see https://wiki.debian.org/RaspberryPiImages
#
# Login and run:
#   sudo make all BUILD_FAMILIES='2 3' BUILD_RELEASES='bullseye'
#
Vagrant.configure("2") do |config|
  memory = 2048
  cpus = 2

  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian-pi-imager"

  config.vm.provider :virtualbox do |c|
    # https://www.vagrantup.com/docs/providers/virtualbox/configuration
    c.memory = memory
    c.cpus = cpus
  end

  config.vm.provision :shell, inline: <<-SHELL
    export DEBIAN_FRONTEND="noninteractive"

    apt-get update
    apt-get upgrade -y

    apt-get install -y \
      vmdb2 \
      dosfstools \
      qemu-utils \
      qemu-user-static \
      debootstrap \
      binfmt-support \
      time \
      kpartx \
      bmap-tools \
      python3 \
      build-essential \
      git

    apt-get install -y fakemachine
  SHELL

  config.vm.provision :shell, privileged: false, inline: <<-SHELL
    mkdir $HOME/src
    cd $HOME/src
    git clone --recursive https://salsa.debian.org/Weltraumschaf/image-specs.git
    cd image-specs
    git checkout custom_images
  SHELL

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
  end
end
