#
# Create own Debian based RaspberyPI images/
#
# see https://wiki.debian.org/RaspberryPiImages
#
Vagrant.configure("2") do |config|
  $vagrant_dir = File.dirname(__FILE__)
  $base_dir = File.dirname($vagrant_dir)

  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian-pi-imager"

  config.vm.synced_folder "#{$vagrant_dir}", "/vagrant", disabled: true
  config.vm.synced_folder "#{$base_dir}", "/vagrant", type: "rsync", :mount_options => ["ro"]
  config.vm.synced_folder "#{ENV["HOME"]}/src/private/image-specs", "/home/vagrant/src/image-specs", type: "rsync", :mount_options => ["rw"]

  config.vm.provision :shell, inline: <<-SHELL
    export DEBIAN_FRONTEND="noninteractive"

    apt-get update
    apt-get upgrade -y

    apt-get install -y \
      vmdb2 \
      dosfstools \
      qemu-utils \
      qemu-user-static \
      debootstrap \
      binfmt-support \
      time \
      kpartx \
      bmap-tools \
      python3 \
      build-essential

    apt-get install -y fakemachine
  SHELL

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
  end
end
