Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.hostname = "debian-plain-local"
    config.vm.network "public_network"

    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.no_install = true
    end
end
