# https://manski.net/2016/09/vagrant-multi-machine-tutorial/

BOX_IMAGE = "debian/bullseye64"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  $vagrant_dir = File.dirname(__FILE__)
  $base_dir = File.dirname($vagrant_dir)

  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "192.168.56.10"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
    end
  end

  config.vm.synced_folder $vagrant_dir, "/vagrant", disabled: true
  config.vm.synced_folder "#{$base_dir}", "/vagrant", type: "rsync", :mount_options => ["ro"]
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/upate-apt.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-linux-tools.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-docker.sh"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = false
  end
end
