# https://manski.net/2016/09/vagrant-multi-machine-tutorial/

BOX_IMAGE = "debian/buster64"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
    config.vm.define "master" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "master"
        subconfig.vm.network :private_network, ip: "10.0.0.10"
    end

    (1..NODE_COUNT).each do |i|
        config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
        end
    end

    config.vm.provision :shell, path: "provision_as_root.sh"

    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.no_install = false
    end
end
