Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "debian-docker-compose"
  config.vm.network "public_network"

  config.vm.provision :shell, path: "../_scripts/install-linux-tools.sh"
  config.vm.provision :shell, path: "../_scripts/install-docker.sh"
  config.vm.provision :shell, path: "../_scripts/install-docker-compose.sh"

  config.vm.provision :shell, privileged: false, path: "../_scripts/install-dotfiles.sh"
  config.vm.provision :shell, privileged: false, path: "../_scripts/install-shell-scripts.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
  end
end
