Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "debian-docker-compose"
  config.vm.network "public_network"
  config.vm.provision :shell, path: "provision_as_root.sh"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = false
  end
end
