Vagrant.configure("2") do |config|
  $vagrant_dir = File.dirname(__FILE__)
  $base_dir = File.dirname($vagrant_dir)

  config.vm.box = "debian/buster64"
  config.vm.hostname = "debian-photoprism"
  config.vm.network "public_network"

  config.vm.synced_folder $vagrant_dir, "/vagrant", disabled: true
  config.vm.synced_folder "#{$base_dir}", "/vagrant", type: "rsync", :mount_options => ["ro"]

  config.vm.network :forwarded_port, guest: 2342, host: 8080
  config.disksize.size = "50GB"

  config.vm.provision :shell, path: "#{$base_dir}/_scripts/upate-apt.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-linux-tools.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-docker.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-docker-compose.sh"
  config.vm.provision :shell, inline: <<-SHELL
    # To mount Samba.
    apt-get install -y \
      cifs-utils
  SHELL

  config.vm.provision :shell, privileged: false, path: "#{$base_dir}/_scripts/install-dotfiles.sh"
  config.vm.provision :shell, privileged: false, path: "#{$base_dir}/_scripts/install-shell-scripts.sh"
  config.vm.provision :file, source: "docker-compose.yml", destination: "docker-compose.yml"
  config.vm.provision :file, source: "start.sh", destination: "start.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
  end
end
