Vagrant.configure("2") do |config|
  $vagrant_dir = File.dirname(__FILE__)
  $base_dir = File.dirname($vagrant_dir)

  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian-local"

  config.vm.synced_folder $vagrant_dir, "/vagrant", disabled: true
  config.vm.synced_folder "#{$base_dir}", "/vagrant", type: "rsync", :mount_options => ["ro"]
  config.vm.synced_folder ENV["HOME"], "/home/vagrant/host"

  config.vm.provision :shell, path: "#{$base_dir}/_scripts/upate-apt.sh"
  config.vm.provision :shell, path: "#{$base_dir}/_scripts/install-linux-tools.sh"
  config.vm.provision :shell, inline: <<-SHELL
    apt-get install -y \
      apt-file \
      build-essential \
      file \
      coreutils \
      man \
      ltrace \
      gdb
  SHELL

  config.vm.provision :shell, privileged: false, path: "#{$base_dir}/_scripts/install-dotfiles.sh"
  config.vm.provision :shell, privileged: false, path: "#{$base_dir}/_scripts/install-shell-scripts.sh"
end
