# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://manski.net/2016/09/vagrant-multi-machine-tutorial/

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"
  config.vm.hostname = "debian"
  # config.vm.network :private_network, ip: "10.0.0.10"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND="noninteractive"
    apt-get update
    apt-get upgrade -y
    apt-get install -y \
        locales \
        git \
        tmux \
        apt-file \
        build-essential \
        file \
        coreutils \
        man \
        ltrace \
        nano \
        gdb \
        curl
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    (
      mkdir -p "${HOME}/src"
      cd "${HOME}/src"
      git clone https://github.com/Weltraumschaf/dotfiles.git
      git clone https://github.com/Weltraumschaf/shell-scripts.git
    )
    (
      cd "${HOME}/src/dotfiles"
      ./install.sh
    )
    (
      cd "${HOME}/src/shell-scripts"
      ./install.sh
    )
  SHELL
end
