Vagrant.configure("2") do |config|

    config.vm.box = "debian/buster64"
    config.vm.hostname = "portainer"
    config.vm.network :forwarded_port, guest: 9000, host: 80
    config.vm.provision :shell, path: "provision_as_root.sh"

    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.no_install = true
    end
end
